### ISSUE TITLE
An error occurred: [Transitive Dependency] react-native-electrode-bridge@1.5.16 was not added to the Mi niApp

### ISSUE THREAD

**Issue by Mikoyan-Gurevich** [electrode-io/electrode-native#956]
I am trying out "building a movie application" tutorial present in docs (https://native.electrode.io/quick-start/getting-started).

Not able to perform below step 
```
$ ern add react-native-ernmovie-api-impl@0.0.15 react-native-ernnavigation-api@0.0.5
``` 
Getting below error 
```
✔ react-native-ernmovie-api-impl is not declared in the manifest. Performing additional checks. 3s
✖ An error occurred: [Transitive Dependency] react-native-electrode-bridge@1.5.16 was not added to the Mi
niApp
```
I kind of tried multiple things, like adding these individually,  installing without version number mentioned. But no luck.

Please help with this one.

**Comment by belemaire** [comment]
Thanks for reporting this issue.

This was due to a wrong version of `react-native-electrode-bridge` dependency being set inside our public manifest (`1.5.15` instead of latest `1.5.15`). 

Fixed by https://github.com/electrode-io/electrode-native-manifest/commit/75622fd7cd873ad95a0c90f590db5a8e2155ac10

If you retry running the command, it should now work.

We'll look into the issue more closely to make sure that this does not happen anymore in the future.

**Comment by nelsonchen5** [comment]
Retried running the command, still having the issue with the error:

`✔ react-native-ernmovie-api-impl is not declared in the manifest. Performing additional checks. 3s
✖ An error occurred: [Transitive Dependency] react-native-electrode-bridge@**1.5.15** was not added to the Mi
niApp`

**Comment by belemaire** [comment]
@nelsonchen5 
Could you please let me know the version of `ern-local-cli` are you using ? 
You can know that by running `ern --version`

**Comment by nelsonchen5** [comment]
@belemaire 

I am using: 

`ℹ ern-local-cli : 0.24.6
ℹ electrode-native : 1.0.15`

**Comment by belemaire** [comment]
@nelsonchen5 
Thanks !
Sorry but I forgot to mention that you should use `react-native-ernmovie-api-impl@0.0.16` instead of `react-native-ernmovie-api-impl@0.0.15`

`ern add react-native-ernmovie-api-impl@0.0.16 react-native-ernnavigation-api@0.0.5`

Will update documentation accordingly.

**Comment by siergiej-jdw** [comment]
I have a similar error now:
`✔ react-native-ernmovie-api-impl is not declared in the manifest. Performing additional checks. 1s
✖ An error occurred: [Transitive Dependency] react-native-electrode-bridge@1.5.19 was not added to the MiniApp`

I guess that maybe the versions aren't updated correctly. Could you take a look, please?
